import { existsSync, mkdirSync, watch, writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';

// 配置
const CORE_DIR = join(process.cwd(), 'pkg/core/src');
const ENTRIES = ['common.ts', 'node.ts', 'browser.ts'];
const CLIENTS_CONFIG = join(process.cwd(), 'core-clients.json');

const HEADER = `// [AUTOGENERATED] DO NOT EDIT! THIS FILE IS A CONCATENATED COPY.
// Original source: luv-sic/pkg/core/src
// To modify, edit the modular source files in luv-sic and run 'bun broadcast-core'\n\n`;

async function getClients() {
  if (!existsSync(CLIENTS_CONFIG)) return [];
  try {
    const content = await Bun.file(CLIENTS_CONFIG).text();
    return JSON.parse(content);
  } catch (e) {
    console.error('❌ 解析 core-clients.json 失败:', e);
    return [];
  }
}

/**
 * 极简的 TS 合并逻辑：将 export * from './xxx' 替换为文件实际内容
 */
function flattenTS(entryPath: string): string {
  const content = readFileSync(entryPath, 'utf-8');
  const lines = content.split('\n');
  const baseDir = dirname(entryPath);
  let flattened = '';

  for (const line of lines) {
    const match = line.match(/export \* from ['"]\.\/(.*)['"]/);
    if (match) {
      const subFilePath = join(baseDir, match[1].endsWith('.ts') ? match[1] : `${match[1]}.ts`);
      if (existsSync(subFilePath)) {
        flattened += `\n// --- Inlined from ${match[1]} ---\n`;
        // 递归处理（如果还有嵌套导出）或直接读取内容并去掉可能冲突的 import
        let subContent = readFileSync(subFilePath, 'utf-8');
        // 简单处理：去掉子文件中的相对导入（因为都被合并到一层了）
        subContent = subContent.replace(/^import .* from ['"]\.\.?\/.*['"]/gm, (m) => `// ${m} (commented out by bundler)`);
        flattened += subContent + '\n';
      }
    } else if (line.trim().startsWith('import')) {
      // 保持外部导入（如 node:fs）
      flattened += line + '\n';
    } else {
      flattened += line + '\n';
    }
  }
  return flattened;
}

async function bundleAndSync() {
  const clients = await getClients();
  console.log(`\n📄 [${new Date().toLocaleTimeString()}] 正在合并并分发核心包 (TS Mode)...`);

  const bundled = new Map<string, string>();
  for (const entry of ENTRIES) {
    const entryPath = join(CORE_DIR, entry);
    if (existsSync(entryPath)) {
      bundled.set(entry, flattenTS(entryPath));
    }
  }

  for (const clientPath of clients) {
    const absoluteClientPath = join(process.cwd(), clientPath);
    if (existsSync(absoluteClientPath)) {
      const dest = join(absoluteClientPath, 'src/@core');
      if (!existsSync(dest)) mkdirSync(dest, { recursive: true });

      for (const [fileName, content] of bundled) {
        writeFileSync(join(dest, fileName), HEADER + content);
      }
      console.log(`✅ 已同步 TS 源码至: ${clientPath}/src/@core`);
    }
  }
}

await bundleAndSync();

if (process.argv.includes('--watch')) {
  console.log('\n👀 正在监听 core/src 变化 (TS Flat Mode)...');
  watch(CORE_DIR, { recursive: true }, async (event, filename) => {
    if (filename && !ENTRIES.includes(filename)) {
       console.log(`📝 模块变更: ${filename}`);
       await bundleAndSync();
    }
  });
}
