import { cpSync, existsSync, mkdirSync, watch, readdirSync, statSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// 配置
const CORE_SRC = join(process.cwd(), 'pkg/core/src');
const CLIENTS_CONFIG = join(process.cwd(), 'core-clients.json');
const HEADER = `// [AUTOGENERATED] DO NOT EDIT! THIS FILE IS A COPY.
// Original source: luv-sic/pkg/core/src
// To modify, edit the source file and run 'bun broadcast-core'\n\n`;

async function getClients() {
  if (!existsSync(CLIENTS_CONFIG)) return [];
  try {
    const content = await Bun.file(CLIENTS_CONFIG).text();
    return JSON.parse(content);
  } catch (e) {
    console.error('❌ 解析 core-clients.json 失败:', e);
    return [];
  }
}

function syncWithHeader(srcDir: string, destDir: string, header: string) {
  const items = readdirSync(srcDir);
  for (const item of items) {
    const srcPath = join(srcDir, item);
    const destPath = join(destDir, item);
    const stats = statSync(srcPath);

    if (stats.isDirectory()) {
      if (!existsSync(destPath)) mkdirSync(destPath, { recursive: true });
      syncWithHeader(srcPath, destPath, header);
    } else if (stats.isFile() && (item.endsWith('.ts') || item.endsWith('.js') || item.endsWith('.tsx'))) {
      const content = readFileSync(srcPath, 'utf-8');
      writeFileSync(destPath, header + content);
    } else {
      // 非代码文件直接拷贝
      cpSync(srcPath, destPath);
    }
  }
}

async function syncToAll() {
  const clients = await getClients();
  console.log(`\n🔄 [${new Date().toLocaleTimeString()}] 开始全量同步 core...`);
  
  for (const clientPath of clients) {
    const absoluteClientPath = join(process.cwd(), clientPath);
    if (existsSync(absoluteClientPath)) {
      const dest = join(absoluteClientPath, 'src/@core');
      if (!existsSync(dest)) mkdirSync(dest, { recursive: true });
      
      syncWithHeader(CORE_SRC, dest, HEADER);
      console.log(`✅ 已同步至: ${clientPath}/src/@core`);
    } else {
      console.warn(`⚠️ 跳过不存在的项目: ${clientPath}`);
    }
  }
}

// 1. 启动时先同步一次
await syncToAll();

// 2. 监听模式
if (process.argv.includes('--watch')) {
  console.log('\n👀 正在监听 core/src 变化...');
  
  const watcher = watch(CORE_SRC, { recursive: true }, async (event, filename) => {
    if (filename) {
      console.log(`📝 检测到变化: ${filename}`);
      await syncToAll();
    }
  });

  process.on('SIGINT', () => {
    watcher.close();
    process.exit();
  });
}
